apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: backend
  annotations:
    kubernetes.io/change-cause: "changed image to nginx:alpine"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-label
  template:
    metadata:
      labels:
        app: pod-label
    spec:
      containers:
      - name: cont1
        image: nginx:alpine
        ports:
        - containerPort: 80
