apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: backend
  annotations:
    kubernetes.io/change-cause: "initial service deployment with nginx:alpine image"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-label
  template:
    metadata:
      labels:
        app: pod-label
    spec:
      containers:
      - name: cont1
        image: nginx:alpine
        ports:
        - containerPort: 80
#425170
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: pod-label
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
