apiVersion: v1
kind: Pod
metadata:
  name: demo-pod2
  labels:
    app: consumer
    env: development
spec:
  containers:
  - name: cont1
    image: nginx:alpine

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod3
  labels:
    app: producer
    env: development
spec:
  containers:
  - name: cont1
    image: nginx:alpine
