apiVersion: v1
kind: ResourceQuota
metadata:
  name: publish-staging
  namespace: publish-staging
spec:
  hard:
    requests:
      cpu: "3"
      memory: 2Gi
    limits:
      cpu: "4"
      memory: 3Gi