apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-replicaset1
  labels:
    app: kafka-test
    env: development
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-label
  template:
    metadata:
      labels:
        app: pod-label
    spec:
      containers:
      - name: cont1
        image: nginx:alpine
