name: deploy and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  # 1. Fast unit tests (outside Docker)
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Install Poetry
        run: pip install poetry==2.1.4

      - name: Install dependencies (including test)
        run: poetry install --with test

      - name: Run unit tests
        run: poetry run pytest tests/ -v --maxfail=3
        env:
          ENV: "testing"

  # 2. Docker build + integration tests
  docker-integration:
    runs-on: ubuntu-latest
    needs: unit-tests   # only run if unit tests pass
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image (test stage)
        run: docker build -f infra/docker/publish.Dockerfile -t myapp-test --target test .

      - name: Run integration tests inside Docker
        run: docker run --rm -e ENV=testing myapp-test

  # 3. Build docker for staging and push production image to aws ECR (only on main)
  build_dockers_for_staging:
    runs-on: [ "self-hosted", "aws", "linux", "x64", "prod" ]
    concurrency:
      group: build-${{ github.ref }}-staging-${{ matrix.name }}
      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - name: Server
            dockerfile: infra/docker/publish.Dockerfile
            image_repo_name: publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build, tag and push Docker image to Amazon ECR
        shell: bash
        run: |
          IMAGE_URI="992382530736.dkr.ecr.us-east-1.amazonaws.com/publish"
          
          echo -e "\e[1;34m---------------------------------------------------------------------------\e[0m"
          echo -e "\e[1;33m  🐳 Building Docker Image for publish \e[1;32m[${{ matrix.dockerfile }}]\e[1;33m\e[0m"
          echo -e "\e[1;34m---------------------------------------------------------------------------\e[0m"

          # Prepare build arguments
          if [ -n "ENV=staging" ]; then
            build_args_str="--build-arg $(echo ENV=staging | sed 's/,/ --build-arg /g')"
          fi
          
          echo "Building Docker image..."
          docker build --cache-from $IMAGE_URI:latest \
                      --file ${{ matrix.dockerfile }} \
                      $build_args_str \
                      --tag $IMAGE_URI:${{ github.run_number }} \
                      --tag $IMAGE_URI:latest .

          echo "Pushing Docker image to ECR..."
          docker push $IMAGE_URI:${{ github.run_number }}
          docker push $IMAGE_URI:latest

          echo -e "\e[1;33m✔✔✔ Uploaded Docker image to Amazon ECR with the following tags: \e[0m\n\e[1;36m- $IMAGE_URI:${{ inputs.tag }}\n- $IMAGE_URI:latest\e[0m"

      - name: Log out of Amazon ECR
        shell: bash
        run: |
          echo "Logging out of Amazon ECR..."
          docker logout 992382530736.dkr.ecr.us-east-1.amazonaws.com
          echo "✔✔✔ Logged out of Amazon ECR. 992382530736.dkr.ecr.us-east-1.amazonaws.com"