name: Format and Lint Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - '**'

jobs:
  format_lint_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.3"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Ruff linter
        run: poetry run ruff check .

      - name: Run Ruff formatter (Black-compatible)
        run: poetry run ruff format --check .

