name: Run Tests

on:
  pull_request:
    branches: 
        - "**"

jobs:
  # 1. Fast unit tests (outside Docker)
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Install Poetry
        run: pip install poetry==2.1.4

      - name: Install dependencies (including test)
        run: poetry install --with test

      - name: Run unit tests
        run: poetry run pytest tests/ -v --maxfail=3
        env:
          ENV: testing

  # 2. Docker build + integration tests
  docker-integration:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image (test stage)
        run: docker build -f infra/docker/publish.Dockerfile -t myapp-test --target test .

      - name: Run integration tests inside Docker
        run: docker run --rm -e ENV=testing myapp-test